SELECT
	CALARMOBJECT.FULLNAME, CALARMREDIRECTIONLIST.DELAY1, CALARMREDIRECTIONLIST.DELAY2
FROM
	CALARMOBJECT INNER JOIN CALARMREDIRECTIONLIST ON CALARMOBJECT.ID = CALARMREDIRECTIONLIST.ID
WHERE
	CALARMOBJECT.FULLNAME LIKE '%Gas System%' AND CALARMOBJECT.FULLNAME LIKE '%Scanner%'
ORDER BY
	"Delay1" ASC
