SELECT
	CASE FRACTIONATOR.STATUS WHEN 5 THEN 255 WHEN 7 THEN 255 ELSE 65280 END AS "~{Background1}", ' ' AS "~Status", METERNUMBER AS "Meter #", NAME AS "Site Name", FLOWRATE AS "Gross Flow Rate", FLOWTODAY AS "Gross Flow Today", PRESSURE, TEMPERATURE, DENSITY, CGROUP.FULLNAME AS "_Name"
FROM
	CGROUP INNER JOIN FRAC ON CGROUP.FULLNAME = FRAC.FULLNAME
WHERE
	( FRAC.FULLNAME LIKE '%%%' )
ORDER BY
	"~Status" ASC, "Meter #" ASC, "Site Name" DESC
